[book]
authors = ["moenarch"]
language = "en"
multilingual = false
src = "./"
title = "Nexiom"

[build]
build-dir = "../html"
create-missing = false

[output.html]
default-theme = "dark"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = true
copy-fonts = true
no-section-label = true
git-repository-url = "https://github.com/moenarch/nexiom"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/moenarch/nexiom/edit/main/guide/{path}"

[output.html.print]
enable = false

[output.html.search]
enable = true

[preprocessor.regex-replacer]
command="mdbook-regex-replacer"

[[preprocessor.regex-replacer.items]]
regex="\\[(?P<message>[\\w ]+)\\]\\(\\.\\./(?P<file>.*)\\.lean\\)"
rep="<a href=\"https://leanprover-community/github.io/lean-web-editor/\" target=\"_blank\" tryitfile=\"../$file.lean\">$message</a>"